#pragma once

#include "array_element_assignment.h"
#include "variable_assignment.h"

#include "if_clause.h"
#include "if_else_clause.h"

#include "and_expression.h"
#include "array_element_expression.h"
#include "boolean_array_allocation_expression.h"
#include "boolean_value_expression.h"
#include "equals_expression.h"
#include "greater_expression.h"
#include "identifier_expression.h"
#include "int_array_allocation_expression.h"
#include "int_value_expression.h"
#include "length_expression.h"
#include "less_expression.h"
#include "minus_expression.h"
#include "negation_expression.h"
#include "or_expression.h"
#include "parentheses_expression.h"
#include "percent_expression.h"
#include "plus_expression.h"
#include "slash_expression.h"
#include "star_expression.h"
#include "unary_minus_expression.h"

#include "assert_statement.h"
#include "assignment_statement.h"
#include "condition_clause_statement.h"
#include "print_statement.h"
#include "scope_statement.h"
#include "variable_declaration_statement.h"
#include "while_cycle_statement.h"

#include "boolean_array_declaration.h"
#include "boolean_variable_declaration.h"
#include "int_array_declaration.h"
#include "int_variable_declaration.h"

#include "main_class.h"
#include "program.h"
#include "statement_list.h"
